configurar keda

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -2,7 +2,7 @@ name: Build and Deploy
 
 on:
   push:
-    branches: [ "main", "develop" ]
+    branches: [ "main", "develop", "deploy-keda" ]
   pull_request:
     branches: [ "main" ]
 
@@ -95,7 +95,7 @@ jobs:
     name: Deploy
     runs-on: ubuntu-latest
     needs: build
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
     
     steps:
       - name: Checkout
@@ -141,6 +141,11 @@ jobs:
           IMAGE_URI: ${{ steps.build-image.outputs.image }}
         run: |
           yq e '.spec.template.spec.containers[0].image = "'"$IMAGE_URI"'"' -i k8s/01-worker-deployment.yaml || { echo "Error updating ecr_image_url_repo_tag value"; exit 1; }
+      
+      - name: Replace queueName and awsRegion in k8s/03-keda-scale.yaml
+        run: |
+          yq e '.spec.triggers[0].metadata.queueName = "'"${{ vars.VIDEOS_PROCESS_SQS_NAME }}"'"' -i k8s/03-keda-scale.yaml || { echo "Error updating queueName"; exit 1; }
+          yq e '.spec.triggers[0].metadata.awsRegion = "'"${{ vars.AWS_REGION }}"'"' -i k8s/03-keda-scale.yaml || { echo "Error updating awsRegion"; exit 1; } 
       
       - name: Deploy to EKS
         run: |
